### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ghost** [Kyrie1965/ttv#1]
Привет,

Получаю ошибку при выполнении ttv.py.

`python3 ttv.py
Traceback (most recent call last):
  File "ttv.py", line 181, in <module>
    response = urllib.request.urlopen(PLAYLIST_LOAD_URL)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

CentOS 7, Python 3.6.7

**Comment by Kyrie1965** [comment]
Привет. Исправлено (теперь оригинальный плейлист с тегами отдаётся в gzip, из-за этого и ошибка была). И добавлена возможность брать ссылки на логотипы из оригинального плейлиста.

**Comment by ghost** [comment]
Спасибо!
